name: Build and Deploy Java Web Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload WAR file
        uses: actions/upload-artifact@v2
        with:
          name: javawebapplication
          path: target/javawebapplication-*.war

  provide-download-link:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download WAR file
        uses: actions/download-artifact@v2
        with:
          name: javawebapplication
          path: target/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate Download Link
        run: |
          echo "Download the built WAR file [here](https://github.com/${{ github.repository }}/raw/${{ github.ref }}/target/javawebapplication-*.war)"
