name: Build and Deploy Java Web Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up latest Java 
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Use the Temurin distribution for the latest LTS version
          java-version: 'latest'
          check-latest: true  # Ensure the latest version is always used

      - name: Build with Maven
        run: mvn clean install

      - name: Upload WAR file
        uses: actions/upload-artifact@v3
        with:
          name: javawebapplication
          path: target/javawebapplication-*.war

  provide-download-link:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download WAR file
        uses: actions/download-artifact@v3
        with:
          name: javawebapplication
          path: target/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Download Link
        run: |
          echo "Download the built WAR file [here](https://github.com/${{ github.repository }}/raw/${{ github.ref }}/target/javawebapplication-*.war)"
