name: Build and Deploy Java Web Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - run: java HelloWorldApp.java
      - name: Build with Maven
        run: mvn clean install
      - name: Upload WAR file
        uses: actions/upload-artifact@v2
        with:
          name: javawebapplication
          path: target/javawebapplication-*.war

  provide-download-link:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download WAR file
        uses: actions/download-artifact@v2
        with:
          name: javawebapplication
          path: target/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate Download Link
        run: |
          echo "Download the built WAR file [here](https://github.com/${{ github.repository }}/raw/${{ github.ref }}/target/javawebapplication-*.war)"
