name: Build and Deploy Java Web Application

on:
  push:						//this workflow runs on everypush on main branch
    branches:
      - main
  workflow_dispatch:		// this cmd will help us to manually run this workflow

jobs:
  build:
    runs-on: ubuntu-latest	//runner is latest ubuntu

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3	//uses version3 of github actions

      - name: Set up Java 17	//install latest java-version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use the Temurin distribution for the latest LTS version
          java-version: '17'
          cache: maven  # Ensure the latest version is always used

      - name: Build with Maven
        run: mvn clean install		//cmd to install maven

      - name: Upload WAR file
        uses: actions/upload-artifact@v3
        with:
          name: javawebapplication
          path: target/javawebapplication-*.war

  provide-download-link:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download WAR file
        uses: actions/download-artifact@v3
        with:
          name: javawebapplication
          path: target/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Download Link
        run: |
          echo "Download the built WAR file [here](https://github.com/${{ github.repository }}/raw/${{ github.ref }}/target/javawebapplication-*.war)"
